### ISSUE TITLE
About the data format

### ISSUE THREAD

**Issue by payne53** [dangoron/BURST#1]
Hi, your codes write very  well, but I'm not quite clear about the format of your input data. It seems to be different from the version from the official web. I'll be quite appreciative if you can give some description or examples about how you organize the input data. Thank you very much.

**Comment by fyang93** [comment]
@payne53 Thank you for your interests in this project and sorry for the late reply.
I manage the [EVVE](http://pascal.inrialpes.fr/data/evve/) dataset with 3 directories: `dataset`, `data` and `result`.
Specifically,
- `dataset` is used to place the original data, like videos, frames, and the extracted features;
- `data` is used to save the embedded video descriptors, you may find details in `embed.py`;
- `result` is used to save retrieved results, `retrieve.py` shows the structure of the result file.

I guess what you most concerned about is the structure of data under `info_dir` in `Makefile`.
A `info_dir` consists of `1_qr`, ..., `13_qr` and `1_db`, ..., `13_db`, e.g., `1_qr` contains the information of query videos in event 1:
```
1db3CxSlSZs.jbl  1MuBD439BY4.jbl  2pKrkVvtWq8.jbl  3y61clq6OQA.jbl  8qBHdRgGxFA.jbl  9rT87-jbiaw.jbl  BXt6gciKXno.jbl
1IHwLTip1nI.jbl  23x6C_YJqTM.jbl  3vJ9zerogbQ.jbl  7BXAejOzOa8.jbl  9hDUVTqxusU.jbl  BOAU395mfJw.jbl
```
where each file is a dumped dictionary with 4 keys `event` (#event), `name` (video name), `length` (number of frames), and `fvecs` (feature vectors):
```
{'event': 1, 'name': '1db3CxSlSZs', 'length': 1917,
 'fvecs': array([[1.35342270e-01, 9.79907274e-01, 3.94127637e-01, ...,
        2.38966435e-01, 1.35551751e-01, 6.47004902e-01],
       [1.02186300e-01, 8.43087018e-01, 3.91412079e-01, ...,
        2.47447267e-01, 7.30684847e-02, 5.56467175e-01],
       ...])
}
```

Please feel free to leave comments, I would explain as best as I can.

**Comment by payne53** [comment]
Thank you. I have got it and modified for other datasets. Thank you very much for your detailed explanation.
